<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class _TblBarangTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_barang')->delete();
        
        \DB::table('tbl_barang')->insert(array (
            0 => 
            array (
                'id_barang' => 2,
                'kode_barang' => 'BRG08',
                'nama_barang' => 'KOMPUTER',
                'unit' => 'AAAA',
                'stok_awal' => 1,
                'stok_sebelumnya' => 82,
                'stok_sekarang' => 74,
                'lokasi_awal' => '2',
                'lokasi_sebelumnya' => 'Lokasi strategis',
                'lokasi_sekarang' => 'Lokasi Blok Q1',
                'status_barang' => 'aktif',
                'id_gedung_create' => 1,
                'id_gudang_create' => 1,
                'id_blok_create' => 1,
                'id_lokasi_create' => 1,
                'id_gedung_now' => 3,
                'id_gudang_now' => 13,
                'id_blok_now' => 4,
                'id_lokasi_now' => 4,
                'id_gedung_old' => 1,
                'id_gudang_old' => 1,
                'id_blok_old' => 1,
                'id_lokasi_old' => 1,
                'id_trx_last' => 99,
                'kode_trx_last' => 'SOM#20230527174923444150',
                'tipe_trx_last' => 'STOK_OUT_MAHASISWA',
                'id_trx_move_last' => 3,
                'kode_trx_move_last' => 'MV#20230522104011779570',
                'user_create' => NULL,
                'user_update' => 'admin',
                'uid' => '339f740c-4b2c-402d-bf10-edd1444be00d',
                'created_at' => '2023-05-15 09:47:51',
                'updated_at' => '2023-05-27 17:49:23',
            ),
            1 => 
            array (
                'id_barang' => 7,
                'kode_barang' => 'AA2',
                'nama_barang' => 'AAA',
                'unit' => 'dddd',
                'stok_awal' => 123,
                'stok_sebelumnya' => 222,
                'stok_sekarang' => 226,
                'lokasi_awal' => 'Lokasi strategis',
                'lokasi_sebelumnya' => 'Lokasi strategis',
                'lokasi_sekarang' => 'Lokaswi2',
                'status_barang' => 'aktif',
                'id_gedung_create' => 1,
                'id_gudang_create' => 1,
                'id_blok_create' => 1,
                'id_lokasi_create' => 1,
                'id_gedung_now' => 2,
                'id_gudang_now' => 2,
                'id_blok_now' => 2,
                'id_lokasi_now' => 2,
                'id_gedung_old' => 1,
                'id_gudang_old' => 1,
                'id_blok_old' => 1,
                'id_lokasi_old' => 1,
                'id_trx_last' => 100,
                'kode_trx_last' => 'SI#20230529021647179938',
                'tipe_trx_last' => 'STOK_IN',
                'id_trx_move_last' => 0,
                'kode_trx_move_last' => '0',
                'user_create' => 'op',
                'user_update' => NULL,
                'uid' => '6a500ef0-fd35-4b7e-9140-b0eb9df8833f',
                'created_at' => '2023-05-20 08:43:06',
                'updated_at' => '2023-05-29 02:16:47',
            ),
            2 => 
            array (
                'id_barang' => 8,
                'kode_barang' => 'BG01',
                'nama_barang' => 'BBBGGG',
                'unit' => 'PO',
                'stok_awal' => 12,
                'stok_sebelumnya' => 10,
                'stok_sekarang' => 8,
                'lokasi_awal' => 'Lokasi strategis',
                'lokasi_sebelumnya' => 'Lokasi strategis',
                'lokasi_sekarang' => 'Lokasi Blok Q2',
                'status_barang' => 'aktif',
                'id_gedung_create' => 1,
                'id_gudang_create' => 1,
                'id_blok_create' => 1,
                'id_lokasi_create' => 1,
                'id_gedung_now' => 3,
                'id_gudang_now' => 14,
                'id_blok_now' => 5,
                'id_lokasi_now' => 5,
                'id_gedung_old' => 1,
                'id_gudang_old' => 1,
                'id_blok_old' => 1,
                'id_lokasi_old' => 1,
                'id_trx_last' => 0,
                'kode_trx_last' => '0',
                'tipe_trx_last' => '',
                'id_trx_move_last' => 3,
                'kode_trx_move_last' => 'MV#20230522104011779570',
                'user_create' => 'op',
                'user_update' => NULL,
                'uid' => '99b76c41-4a7a-420b-ab0a-5dd7ea275fec',
                'created_at' => '2023-05-20 08:44:53',
                'updated_at' => '2023-05-22 10:40:11',
            ),
            3 => 
            array (
                'id_barang' => 11,
                'kode_barang' => 'PRY01',
                'nama_barang' => 'Proyektor BenQ',
                'unit' => 'PCS',
                'stok_awal' => 5,
                'stok_sebelumnya' => 44,
                'stok_sekarang' => 42,
                'lokasi_awal' => 'Lokasi Blok Q1',
                'lokasi_sebelumnya' => 'Lokasi Blok Q2',
                'lokasi_sekarang' => 'ZZZ',
                'status_barang' => 'aktif',
                'id_gedung_create' => 3,
                'id_gudang_create' => 13,
                'id_blok_create' => 4,
                'id_lokasi_create' => 4,
                'id_gedung_now' => 2,
                'id_gudang_now' => 7,
                'id_blok_now' => 6,
                'id_lokasi_now' => 7,
                'id_gedung_old' => 3,
                'id_gudang_old' => 14,
                'id_blok_old' => 5,
                'id_lokasi_old' => 5,
                'id_trx_last' => 99,
                'kode_trx_last' => 'SOM#20230527174923444150',
                'tipe_trx_last' => 'STOK_OUT_MAHASISWA',
                'id_trx_move_last' => 6,
                'kode_trx_move_last' => 'MV#20230529020932057501',
                'user_create' => 'admin',
                'user_update' => 'admin',
                'uid' => '73d6634f-dbb5-4f35-accb-df3a0f053029',
                'created_at' => '2023-05-22 11:34:01',
                'updated_at' => '2023-05-29 02:09:32',
            ),
            4 => 
            array (
                'id_barang' => 16,
                'kode_barang' => 'BR0999',
                'nama_barang' => 'coba',
                'unit' => 'P',
                'stok_awal' => 12,
                'stok_sebelumnya' => 0,
                'stok_sekarang' => 12,
                'lokasi_awal' => 'Lokasi Blok Q1',
                'lokasi_sebelumnya' => NULL,
                'lokasi_sekarang' => 'Lokasi Blok Q1',
                'status_barang' => 'nonaktif',
                'id_gedung_create' => 3,
                'id_gudang_create' => 13,
                'id_blok_create' => 4,
                'id_lokasi_create' => 4,
                'id_gedung_now' => 3,
                'id_gudang_now' => 13,
                'id_blok_now' => 4,
                'id_lokasi_now' => 4,
                'id_gedung_old' => NULL,
                'id_gudang_old' => NULL,
                'id_blok_old' => NULL,
                'id_lokasi_old' => NULL,
                'id_trx_last' => NULL,
                'kode_trx_last' => NULL,
                'tipe_trx_last' => NULL,
                'id_trx_move_last' => NULL,
                'kode_trx_move_last' => NULL,
                'user_create' => 'admin',
                'user_update' => 'admin',
                'uid' => 'e6869098-1bb1-41d3-9e25-01132e64f777',
                'created_at' => '2023-06-05 00:27:18',
                'updated_at' => '2023-06-05 00:27:54',
            ),
        ));
        
        
    }
}