<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class _TblTrxBarangPindahDetailTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_trx_barang_pindah_detail')->delete();
        
        \DB::table('tbl_trx_barang_pindah_detail')->insert(array (
            0 => 
            array (
                'id' => 1,
                'id_pindah' => NULL,
                'kode_pindah' => 'MV#20230522103754002527',
                'norut' => 1,
                'id_pindah_sebelumnya' => NULL,
                'id_barang' => 2,
                'kode_barang' => 'BRG08',
                'nama_barang' => 'KOMPUTER',
                'lokasi_sebelumnya' => NULL,
                'lokasi_sekarang' => 'Lokasi Blok Q1',
                'id_gedung' => 3,
                'id_gudang' => 13,
                'id_blok' => 4,
                'id_lokasi' => 4,
                'nama_gedung' => 'GEDUNG Q',
                'nama_gudang' => 'Ruang Q1',
                'nama_blok' => 'Blok Q1',
                'nama_lokasi' => 'Lokasi Blok Q1',
                'stok' => 1,
                'user_create' => NULL,
                'user_update' => NULL,
                'uid' => 'c6bdda3f-c354-494c-95b1-d4fedf4ff6b9',
                'created_at' => '2023-05-22 10:37:54',
                'updated_at' => '2023-05-22 10:37:54',
            ),
            1 => 
            array (
                'id' => 2,
                'id_pindah' => NULL,
                'kode_pindah' => 'MV#20230522103754002527',
                'norut' => 2,
                'id_pindah_sebelumnya' => NULL,
                'id_barang' => 8,
                'kode_barang' => 'BG01',
                'nama_barang' => 'BBBGGG',
                'lokasi_sebelumnya' => NULL,
                'lokasi_sekarang' => 'Lokasi Blok Q2',
                'id_gedung' => 3,
                'id_gudang' => 14,
                'id_blok' => 5,
                'id_lokasi' => 5,
                'nama_gedung' => 'GEDUNG Q',
                'nama_gudang' => 'Ruang Q2',
                'nama_blok' => 'Blok Q2',
                'nama_lokasi' => 'Lokasi Blok Q2',
                'stok' => 2,
                'user_create' => NULL,
                'user_update' => NULL,
                'uid' => '62e306c7-de89-4287-ae2d-2d067d764d9b',
                'created_at' => '2023-05-22 10:37:54',
                'updated_at' => '2023-05-22 10:37:54',
            ),
            2 => 
            array (
                'id' => 3,
                'id_pindah' => 2,
                'kode_pindah' => 'MV#20230522103859713893',
                'norut' => 1,
                'id_pindah_sebelumnya' => NULL,
                'id_barang' => 2,
                'kode_barang' => 'BRG08',
                'nama_barang' => 'KOMPUTER',
                'lokasi_sebelumnya' => NULL,
                'lokasi_sekarang' => 'Lokasi Blok Q1',
                'id_gedung' => 3,
                'id_gudang' => 13,
                'id_blok' => 4,
                'id_lokasi' => 4,
                'nama_gedung' => 'GEDUNG Q',
                'nama_gudang' => 'Ruang Q1',
                'nama_blok' => 'Blok Q1',
                'nama_lokasi' => 'Lokasi Blok Q1',
                'stok' => 1,
                'user_create' => NULL,
                'user_update' => NULL,
                'uid' => '1d8cafff-ed51-4533-aa72-9d0305d03ed7',
                'created_at' => '2023-05-22 10:38:59',
                'updated_at' => '2023-05-22 10:38:59',
            ),
            3 => 
            array (
                'id' => 4,
                'id_pindah' => 2,
                'kode_pindah' => 'MV#20230522103859713893',
                'norut' => 2,
                'id_pindah_sebelumnya' => NULL,
                'id_barang' => 8,
                'kode_barang' => 'BG01',
                'nama_barang' => 'BBBGGG',
                'lokasi_sebelumnya' => NULL,
                'lokasi_sekarang' => 'Lokasi Blok Q2',
                'id_gedung' => 3,
                'id_gudang' => 14,
                'id_blok' => 5,
                'id_lokasi' => 5,
                'nama_gedung' => 'GEDUNG Q',
                'nama_gudang' => 'Ruang Q2',
                'nama_blok' => 'Blok Q2',
                'nama_lokasi' => 'Lokasi Blok Q2',
                'stok' => 2,
                'user_create' => NULL,
                'user_update' => NULL,
                'uid' => 'c999bfc1-e984-4d5c-b1f1-145f2b8a7d68',
                'created_at' => '2023-05-22 10:38:59',
                'updated_at' => '2023-05-22 10:38:59',
            ),
            4 => 
            array (
                'id' => 5,
                'id_pindah' => 3,
                'kode_pindah' => 'MV#20230522104011779570',
                'norut' => 1,
                'id_pindah_sebelumnya' => NULL,
                'id_barang' => 2,
                'kode_barang' => 'BRG08',
                'nama_barang' => 'KOMPUTER',
                'lokasi_sebelumnya' => NULL,
                'lokasi_sekarang' => 'Lokasi Blok Q1',
                'id_gedung' => 3,
                'id_gudang' => 13,
                'id_blok' => 4,
                'id_lokasi' => 4,
                'nama_gedung' => 'GEDUNG Q',
                'nama_gudang' => 'Ruang Q1',
                'nama_blok' => 'Blok Q1',
                'nama_lokasi' => 'Lokasi Blok Q1',
                'stok' => 1,
                'user_create' => NULL,
                'user_update' => NULL,
                'uid' => 'e6ea9679-6342-414b-a225-1f6f599b7382',
                'created_at' => '2023-05-22 10:40:11',
                'updated_at' => '2023-05-22 10:40:11',
            ),
            5 => 
            array (
                'id' => 6,
                'id_pindah' => 3,
                'kode_pindah' => 'MV#20230522104011779570',
                'norut' => 2,
                'id_pindah_sebelumnya' => NULL,
                'id_barang' => 8,
                'kode_barang' => 'BG01',
                'nama_barang' => 'BBBGGG',
                'lokasi_sebelumnya' => NULL,
                'lokasi_sekarang' => 'Lokasi Blok Q2',
                'id_gedung' => 3,
                'id_gudang' => 14,
                'id_blok' => 5,
                'id_lokasi' => 5,
                'nama_gedung' => 'GEDUNG Q',
                'nama_gudang' => 'Ruang Q2',
                'nama_blok' => 'Blok Q2',
                'nama_lokasi' => 'Lokasi Blok Q2',
                'stok' => 2,
                'user_create' => NULL,
                'user_update' => NULL,
                'uid' => 'd254f9ea-aaba-4813-8dfb-5f52d4bafb41',
                'created_at' => '2023-05-22 10:40:11',
                'updated_at' => '2023-05-22 10:40:11',
            ),
            6 => 
            array (
                'id' => 7,
                'id_pindah' => 4,
                'kode_pindah' => 'MV#20230522113721081127',
                'norut' => 1,
                'id_pindah_sebelumnya' => NULL,
                'id_barang' => 11,
                'kode_barang' => 'PRY01',
                'nama_barang' => 'Proyektor BenQ',
                'lokasi_sebelumnya' => NULL,
                'lokasi_sekarang' => 'Lokasi Blok Q2',
                'id_gedung' => 3,
                'id_gudang' => 14,
                'id_blok' => 5,
                'id_lokasi' => 5,
                'nama_gedung' => 'GEDUNG Q',
                'nama_gudang' => 'Ruang Q2',
                'nama_blok' => 'Blok Q2',
                'nama_lokasi' => 'Lokasi Blok Q2',
                'stok' => 1,
                'user_create' => NULL,
                'user_update' => NULL,
                'uid' => '403acd2f-0491-4aef-a98b-2f045eb4eb30',
                'created_at' => '2023-05-22 11:37:21',
                'updated_at' => '2023-05-22 11:37:21',
            ),
            7 => 
            array (
                'id' => 8,
                'id_pindah' => 6,
                'kode_pindah' => 'MV#20230529020932057501',
                'norut' => 1,
                'id_pindah_sebelumnya' => NULL,
                'id_barang' => 11,
                'kode_barang' => 'PRY01',
                'nama_barang' => 'Proyektor BenQ',
                'lokasi_sebelumnya' => NULL,
                'lokasi_sekarang' => 'ZZZ',
                'id_gedung' => 2,
                'id_gudang' => 7,
                'id_blok' => 6,
                'id_lokasi' => 7,
                'nama_gedung' => 'GSG Lantai 2',
                'nama_gudang' => 'Ruang Teknisi',
                'nama_blok' => 'XXXXXX',
                'nama_lokasi' => 'ZZZ',
                'stok' => 2,
                'user_create' => NULL,
                'user_update' => NULL,
                'uid' => 'aff8d16a-6823-4bb4-a405-271591f95f1c',
                'created_at' => '2023-05-29 02:09:32',
                'updated_at' => '2023-05-29 02:09:32',
            ),
        ));
        
        
    }
}